/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    artworks: Artwork;
    derivatives: Derivative;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    artworks: ArtworksSelect<false> | ArtworksSelect<true>;
    derivatives: DerivativesSelect<false> | DerivativesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    mainNavigation: MainNavigation;
  };
  globalsSelect: {
    mainNavigation: MainNavigationSelect<false> | MainNavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  slugManualOverride?: boolean | null;
  /**
   * Build the page with one- or two-column layout sections.
   */
  layout?:
    | {
        /**
         * Controls the centered max inline size of this section.
         */
        width: 'small' | 'medium' | 'large' | 'full';
        columns: 'one' | 'two';
        /**
         * Available in single-column sections. Includes the artwork grid.
         */
        blocks?:
          | (
              | {
                  content: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'richText';
                }
              | {
                  image: {
                    source: number | Media;
                    selectedPresetKey?: ('1_1' | '4_3' | '2_3' | '3_2') | null;
                    presets?: {
                      '1_1'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '4_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '2_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '3_2'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                    };
                  };
                  caption?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'captionImage';
                }
              | {
                  poster?: {
                    source?: (number | null) | Media;
                    selectedPresetKey?: ('1_1' | '4_3' | '16_9') | null;
                    presets?: {
                      '1_1'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '4_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '16_9'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                    };
                  };
                  av1File?: (number | null) | Media;
                  h264File?: (number | null) | Media;
                  ratio: '16_9' | '4_3' | '1_1';
                  maxWidth?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'video';
                }
              | {
                  items?:
                    | {
                        label: string;
                        link: string;
                        description?: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        } | null;
                        screenshot?: {
                          source?: (number | null) | Media;
                          selectedPresetKey?: '1_1' | null;
                          presets?: {
                            '1_1'?: {
                              crop?: {
                                x?: number | null;
                                y?: number | null;
                                zoom?: number | null;
                              };
                              derivative?: (number | null) | Derivative;
                              state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                              fingerprint?: string | null;
                              sourceVersion?: string | null;
                              lastGeneratedAt?: string | null;
                              lastError?: string | null;
                            };
                          };
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'linkList';
                }
              | {
                  /**
                   * Drag to reorder artworks.
                   */
                  items?:
                    | {
                        artwork: number | Artwork;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'artworkGrid';
                }
              | {
                  form?: (number | null) | Form;
                  heading?: string | null;
                  intro?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'formReference';
                }
            )[]
          | null;
        /**
         * Controls the width balance between the primary and secondary columns.
         */
        ratio?: ('1_1' | '3_2' | '2_3') | null;
        primaryBlocks?:
          | (
              | {
                  content: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'richText';
                }
              | {
                  image: {
                    source: number | Media;
                    selectedPresetKey?: ('1_1' | '4_3' | '2_3' | '3_2') | null;
                    presets?: {
                      '1_1'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '4_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '2_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '3_2'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                    };
                  };
                  caption?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'captionImage';
                }
              | {
                  poster?: {
                    source?: (number | null) | Media;
                    selectedPresetKey?: ('1_1' | '4_3' | '16_9') | null;
                    presets?: {
                      '1_1'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '4_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '16_9'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                    };
                  };
                  av1File?: (number | null) | Media;
                  h264File?: (number | null) | Media;
                  ratio: '16_9' | '4_3' | '1_1';
                  maxWidth?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'video';
                }
              | {
                  items?:
                    | {
                        label: string;
                        link: string;
                        description?: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        } | null;
                        screenshot?: {
                          source?: (number | null) | Media;
                          selectedPresetKey?: '1_1' | null;
                          presets?: {
                            '1_1'?: {
                              crop?: {
                                x?: number | null;
                                y?: number | null;
                                zoom?: number | null;
                              };
                              derivative?: (number | null) | Derivative;
                              state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                              fingerprint?: string | null;
                              sourceVersion?: string | null;
                              lastGeneratedAt?: string | null;
                              lastError?: string | null;
                            };
                          };
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'linkList';
                }
              | {
                  form?: (number | null) | Form;
                  heading?: string | null;
                  intro?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'formReference';
                }
            )[]
          | null;
        secondaryBlocks?:
          | (
              | {
                  content: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'richText';
                }
              | {
                  image: {
                    source: number | Media;
                    selectedPresetKey?: ('1_1' | '4_3' | '2_3' | '3_2') | null;
                    presets?: {
                      '1_1'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '4_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '2_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '3_2'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                    };
                  };
                  caption?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'captionImage';
                }
              | {
                  poster?: {
                    source?: (number | null) | Media;
                    selectedPresetKey?: ('1_1' | '4_3' | '16_9') | null;
                    presets?: {
                      '1_1'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '4_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '16_9'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                    };
                  };
                  av1File?: (number | null) | Media;
                  h264File?: (number | null) | Media;
                  ratio: '16_9' | '4_3' | '1_1';
                  maxWidth?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'video';
                }
              | {
                  items?:
                    | {
                        label: string;
                        link: string;
                        description?: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        } | null;
                        screenshot?: {
                          source?: (number | null) | Media;
                          selectedPresetKey?: '1_1' | null;
                          presets?: {
                            '1_1'?: {
                              crop?: {
                                x?: number | null;
                                y?: number | null;
                                zoom?: number | null;
                              };
                              derivative?: (number | null) | Derivative;
                              state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                              fingerprint?: string | null;
                              sourceVersion?: string | null;
                              lastGeneratedAt?: string | null;
                              lastError?: string | null;
                            };
                          };
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'linkList';
                }
              | {
                  form?: (number | null) | Form;
                  heading?: string | null;
                  intro?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'formReference';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "derivatives".
 */
export interface Derivative {
  id: number;
  source: number | Media;
  sourceCollection?: string | null;
  sourceID?: string | null;
  sourceVersion?: string | null;
  ownerKind: 'collection' | 'global';
  ownerSlug?: string | null;
  ownerID?: string | null;
  fieldPath?: string | null;
  usagePath?: string | null;
  presetKey?: string | null;
  presetAspectRatio?: string | null;
  fingerprint?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks".
 */
export interface Artwork {
  id: number;
  title: string;
  slug: string;
  slugManualOverride?: boolean | null;
  medium?: string | null;
  measure?: string | null;
  year?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: {
    source?: (number | null) | Media;
    selectedPresetKey?: '1_1' | null;
    presets?: {
      '1_1'?: {
        crop?: {
          x?: number | null;
          y?: number | null;
          zoom?: number | null;
        };
        derivative?: (number | null) | Derivative;
        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
        fingerprint?: string | null;
        sourceVersion?: string | null;
        lastGeneratedAt?: string | null;
        lastError?: string | null;
      };
    };
  };
  documentationSections?:
    | (
        | {
            layout: 'Image' | 'Grid 1/1' | 'Grid 1/2' | 'Grid 2/1' | 'Grid 2/2' | 'Grid 1/1/1' | 'Grid 1/1/2';
            /**
             * Add the exact number of image rows required by the selected layout.
             */
            items?:
              | {
                  image: {
                    source: number | Media;
                    selectedPresetKey?: ('1_1' | '4_3' | '2_3' | '3_2') | null;
                    presets?: {
                      '1_1'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '4_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '2_3'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                      '3_2'?: {
                        crop?: {
                          x?: number | null;
                          y?: number | null;
                          zoom?: number | null;
                        };
                        derivative?: (number | null) | Derivative;
                        state?: ('unsaved' | 'missing' | 'ready' | 'stale' | 'generating' | 'failed') | null;
                        fingerprint?: string | null;
                        sourceVersion?: string | null;
                        lastGeneratedAt?: string | null;
                        lastError?: string | null;
                      };
                    };
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'docGrid';
          }
        | {
            items?:
              | {
                  media: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'docAudio';
          }
        | {
            items?:
              | {
                  media: number | Media;
                  ratio: '16_9' | '4_3' | '1_1';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'docVideo';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'artworks';
        value: number | Artwork;
      } | null)
    | ({
        relationTo: 'derivatives';
        value: number | Derivative;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugManualOverride?: T;
  layout?:
    | T
    | {
        width?: T;
        columns?: T;
        blocks?:
          | T
          | {
              richText?:
                | T
                | {
                    content?: T;
                    id?: T;
                    blockName?: T;
                  };
              captionImage?:
                | T
                | {
                    image?:
                      | T
                      | {
                          source?: T;
                          selectedPresetKey?: T;
                          presets?:
                            | T
                            | {
                                '1_1'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '4_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '2_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '3_2'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                              };
                        };
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
              video?:
                | T
                | {
                    poster?:
                      | T
                      | {
                          source?: T;
                          selectedPresetKey?: T;
                          presets?:
                            | T
                            | {
                                '1_1'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '4_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '16_9'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                              };
                        };
                    av1File?: T;
                    h264File?: T;
                    ratio?: T;
                    maxWidth?: T;
                    id?: T;
                    blockName?: T;
                  };
              linkList?:
                | T
                | {
                    items?:
                      | T
                      | {
                          label?: T;
                          link?: T;
                          description?: T;
                          screenshot?:
                            | T
                            | {
                                source?: T;
                                selectedPresetKey?: T;
                                presets?:
                                  | T
                                  | {
                                      '1_1'?:
                                        | T
                                        | {
                                            crop?:
                                              | T
                                              | {
                                                  x?: T;
                                                  y?: T;
                                                  zoom?: T;
                                                };
                                            derivative?: T;
                                            state?: T;
                                            fingerprint?: T;
                                            sourceVersion?: T;
                                            lastGeneratedAt?: T;
                                            lastError?: T;
                                          };
                                    };
                              };
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              artworkGrid?:
                | T
                | {
                    items?:
                      | T
                      | {
                          artwork?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              formReference?:
                | T
                | {
                    form?: T;
                    heading?: T;
                    intro?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        ratio?: T;
        primaryBlocks?:
          | T
          | {
              richText?:
                | T
                | {
                    content?: T;
                    id?: T;
                    blockName?: T;
                  };
              captionImage?:
                | T
                | {
                    image?:
                      | T
                      | {
                          source?: T;
                          selectedPresetKey?: T;
                          presets?:
                            | T
                            | {
                                '1_1'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '4_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '2_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '3_2'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                              };
                        };
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
              video?:
                | T
                | {
                    poster?:
                      | T
                      | {
                          source?: T;
                          selectedPresetKey?: T;
                          presets?:
                            | T
                            | {
                                '1_1'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '4_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '16_9'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                              };
                        };
                    av1File?: T;
                    h264File?: T;
                    ratio?: T;
                    maxWidth?: T;
                    id?: T;
                    blockName?: T;
                  };
              linkList?:
                | T
                | {
                    items?:
                      | T
                      | {
                          label?: T;
                          link?: T;
                          description?: T;
                          screenshot?:
                            | T
                            | {
                                source?: T;
                                selectedPresetKey?: T;
                                presets?:
                                  | T
                                  | {
                                      '1_1'?:
                                        | T
                                        | {
                                            crop?:
                                              | T
                                              | {
                                                  x?: T;
                                                  y?: T;
                                                  zoom?: T;
                                                };
                                            derivative?: T;
                                            state?: T;
                                            fingerprint?: T;
                                            sourceVersion?: T;
                                            lastGeneratedAt?: T;
                                            lastError?: T;
                                          };
                                    };
                              };
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              formReference?:
                | T
                | {
                    form?: T;
                    heading?: T;
                    intro?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        secondaryBlocks?:
          | T
          | {
              richText?:
                | T
                | {
                    content?: T;
                    id?: T;
                    blockName?: T;
                  };
              captionImage?:
                | T
                | {
                    image?:
                      | T
                      | {
                          source?: T;
                          selectedPresetKey?: T;
                          presets?:
                            | T
                            | {
                                '1_1'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '4_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '2_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '3_2'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                              };
                        };
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
              video?:
                | T
                | {
                    poster?:
                      | T
                      | {
                          source?: T;
                          selectedPresetKey?: T;
                          presets?:
                            | T
                            | {
                                '1_1'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '4_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '16_9'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                              };
                        };
                    av1File?: T;
                    h264File?: T;
                    ratio?: T;
                    maxWidth?: T;
                    id?: T;
                    blockName?: T;
                  };
              linkList?:
                | T
                | {
                    items?:
                      | T
                      | {
                          label?: T;
                          link?: T;
                          description?: T;
                          screenshot?:
                            | T
                            | {
                                source?: T;
                                selectedPresetKey?: T;
                                presets?:
                                  | T
                                  | {
                                      '1_1'?:
                                        | T
                                        | {
                                            crop?:
                                              | T
                                              | {
                                                  x?: T;
                                                  y?: T;
                                                  zoom?: T;
                                                };
                                            derivative?: T;
                                            state?: T;
                                            fingerprint?: T;
                                            sourceVersion?: T;
                                            lastGeneratedAt?: T;
                                            lastError?: T;
                                          };
                                    };
                              };
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              formReference?:
                | T
                | {
                    form?: T;
                    heading?: T;
                    intro?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks_select".
 */
export interface ArtworksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugManualOverride?: T;
  medium?: T;
  measure?: T;
  year?: T;
  description?: T;
  coverImage?:
    | T
    | {
        source?: T;
        selectedPresetKey?: T;
        presets?:
          | T
          | {
              '1_1'?:
                | T
                | {
                    crop?:
                      | T
                      | {
                          x?: T;
                          y?: T;
                          zoom?: T;
                        };
                    derivative?: T;
                    state?: T;
                    fingerprint?: T;
                    sourceVersion?: T;
                    lastGeneratedAt?: T;
                    lastError?: T;
                  };
            };
      };
  documentationSections?:
    | T
    | {
        docGrid?:
          | T
          | {
              layout?: T;
              items?:
                | T
                | {
                    image?:
                      | T
                      | {
                          source?: T;
                          selectedPresetKey?: T;
                          presets?:
                            | T
                            | {
                                '1_1'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '4_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '2_3'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                                '3_2'?:
                                  | T
                                  | {
                                      crop?:
                                        | T
                                        | {
                                            x?: T;
                                            y?: T;
                                            zoom?: T;
                                          };
                                      derivative?: T;
                                      state?: T;
                                      fingerprint?: T;
                                      sourceVersion?: T;
                                      lastGeneratedAt?: T;
                                      lastError?: T;
                                    };
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        docAudio?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        docVideo?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    ratio?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "derivatives_select".
 */
export interface DerivativesSelect<T extends boolean = true> {
  source?: T;
  sourceCollection?: T;
  sourceID?: T;
  sourceVersion?: T;
  ownerKind?: T;
  ownerSlug?: T;
  ownerID?: T;
  fieldPath?: T;
  usagePath?: T;
  presetKey?: T;
  presetAspectRatio?: T;
  fingerprint?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mainNavigation".
 */
export interface MainNavigation {
  id: number;
  items?:
    | {
        label: string;
        document:
          | {
              relationTo: 'pages';
              value: number | Page;
            }
          | {
              relationTo: 'artworks';
              value: number | Artwork;
            };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mainNavigation_select".
 */
export interface MainNavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        document?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}